[install]
state = enabled
build = 2

[launcher]
description = Splunk TA for Mikrotik RouterOS - syslog parsing and CIM normalization (v6 and v7)
author = neokjames (forked from Andreas Roth)
version = 1.0.0

[ui]
is_visible = 0
label = TA-routeros

[package]
id = TA-routeros
check_for_updates = 1
